// Authentication
export const STORE_USER_DATA = 'STORE_USER_DATA';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const RESET_AUTH_ERRORS = 'RESET_AUTH_ERRORS';

// Users
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
export const REMOVE_USER_START = 'REMOVE_USER_START';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';

// Meals
export const FETCH_MEALS_START = 'FETCH_MEALS_START';
export const FETCH_MEALS_SUCCESS = 'FETCH_MEALS_SUCCESS';
export const FETCH_MEALS_FAILURE = 'FETCH_MEALS_FAILURE';
export const CREATE_MEAL_START = 'CREATE_MEAL_START';
export const CREATE_MEAL_SUCCESS = 'CREATE_MEAL_SUCCESS';
export const CREATE_MEAL_FAILURE = 'CREATE_MEAL_FAILURE';
export const UPDATE_MEAL_START = 'UPDATE_MEAL_START';
export const UPDATE_MEAL_SUCCESS = 'UPDATE_MEAL_SUCCESS';
export const UPDATE_MEAL_FAILURE = 'UPDATE_MEAL_FAILURE';
export const REMOVE_MEAL_START = 'REMOVE_MEAL_START';
export const REMOVE_MEAL_SUCCESS = 'REMOVE_MEAL_SUCCESS';
export const REMOVE_MEAL_FAILURE = 'REMOVE_MEAL_FAILURE';
export const FILTER_MEALS = 'FILTER_MEALS';
export const RESET_MEALS_FILTERS = 'RESET_MEALS_FILTERS';
